---
- name: installing weblayer
 hosts: web
 user: root
 become: yes

 tasks:
 - name: install apache
   yum:
     name: httpd
     state: present
 - name: start the apache
   service:
     name: httpd
     state: started
